### ISSUE TITLE
A smart contract pattern to save gas

### ISSUE THREAD

**Issue by mudgen** [iskdrews/awesome-solidity-gas-optimization#1]
New article here about saving gas for larger smart contract systems.   Should this be added to the awesome list?

https://eip2535diamonds.substack.com/p/how-eip2535-diamonds-reduces-gas

**Comment by iskdrews** [comment]
Thanks so much, @mudgen, would you mind please PR it? I would like really to be a contributor to the awesome list.

**Comment by iskdrews** [comment]
I've added it @mudgen, thanks so much.
