### ISSUE TITLE
Add "A Collection of Gas Optimisation Tricks"

### ISSUE THREAD

**Issue by pcaversaccio** [iskdrews/awesome-solidity-gas-optimization#4]
I've put together a long list of optimisations in the OpenZeppelin forum: [A Collection of Gas Optimisation Tricks](https://forum.openzeppelin.com/t/a-collection-of-gas-optimisation-tricks/19966). Please consider adding it to your README.

**Comment by iskdrews** [comment]
Thanks so much, @pcaversaccio, could you please create a PR with them?
